POST http://127.0.0.1:8080/users/register
accept: application/json
Content-Type: application/json

{
  "username": "bob",
  "email": "bob@example.com",
  "password": "bob"
}

> {%
client.global.set("id_bob", response.body.uid);

%}
###

POST http://127.0.0.1:8080/users/register
accept: application/json
Content-Type: application/json

{
  "username": "mike",
  "email": "mike@example.com",
  "password": "mike"
}

> {%
client.global.set("mike", response.body.uid);

%}


###
POST http://127.0.0.1:8080/token
Content-Type: application/x-www-form-urlencoded
accept: application/json

grant_type=&username=mike&password=mike&scope=&client_id=&client_secret=

> {%
client.global.set("access_token", response.body.access_token);

%}

###

POST http://127.0.0.1:8080/events/register?title=test_mike&description=test&location=test&tags=%23fitness&tags=%23gaming&
    tags=%23lecture&tags=%23photography&tags=%23travel&start_time=1705491930.0598893&end_time=1705491930.0598893
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded

> {%
 client.global.set("id_event_mike", response.body.id_event);
%}


###
POST http://127.0.0.1:8080/token
Content-Type: application/x-www-form-urlencoded
accept: application/json

grant_type=&username=bob&password=bob&scope=&client_id=&client_secret=

> {%
client.global.set("access_token", response.body.access_token);

%}

###

POST http://127.0.0.1:8080/events/register?title=test_bob&description=test&location=test&tags=%23fitness&tags=%23gaming&
    tags=%23lecture&tags=%23photography&tags=%23travel&start_time=1705491930.0598893&end_time=1705491930.0598893
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/x-www-form-urlencoded

> {%
 client.global.set("id_event_bob", response.body.id_event);
%}

###

GET http://127.0.0.1:8080/events/test
accept: application/json

###
GET http://127.0.0.1:8080/events
accept: application/json
###


PUT http://127.0.0.1:8080/events/{{id_event_bob}}/admin
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
"username": "mike"
}

###


DELETE http://127.0.0.1:8080/events/{{id_event_bob}}/admin
accept: application/json
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "admin_id": "{{id_mike}}"
}

###
